name: Deploy to Heroku

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Heroku Container Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "$HEROKU_API_KEY" | docker login --username=_ --password-stdin registry.heroku.com

      - name: Build and push Docker image to Heroku
        env:
          HEROKU_APP_NAME: family-central
        run: |
          docker build -t registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web .
          docker push registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web

      - name: Release to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: family-central
        run: |
          curl -n -X PATCH https://api.heroku.com/apps/${{ env.HEROKU_APP_NAME }}/formation \
          -d '{
            "updates": [
              {
                "type": "web",
                "docker_image": "'"$(docker inspect registry.heroku.com/${{ env.HEROKU_APP_NAME }}/web:latest --format={{.Id}})"'"
              }
            ]
          }' \
          -H "Content-Type: application/json" \
          -H "Accept: application/vnd.heroku+json; version=3.docker-releases" \
          -H "Authorization: Bearer $HEROKU_API_KEY"
